Chore: Fix: Fix a bug with Composer v2 that caused an error
The PHP error:
Fatal error: Uncaught Error: Call to undefined method JonnyW\PhantomJs\Client::isLazy() in ...include\class\Browser\PhantomJSWrapper.php:42

This is due to dependency conflicts.

Fixes #4.